### PR TITLE
Issue #12 - Added footer

### PR DESCRIPTION
**Pull request by EChesters**
## What this does
- Added footer React component.
- All links work - on website and Github & Twitter social media
- No styling

## Screenshots
screen shot 2017-02-06 at 22 53 35

### CODE REVIEW

**Comment by EChesters** [comment]
I'm guessing bundle.js under src/assets/javascript needs to be ignored? It's generated by `webpack` and is being a pain in the arse when committing and running `webpack --watch`.

**Review by tanyapowell — COMMENTED** [review]
Just one thing: 
- the `bundle.js` and `bundle.js.map` should be added to the `.gitnore` and not committed

**Review by tanyapowell — CHANGES_REQUESTED** [review]
Just one thing: 
- the `bundle.js` and `bundle.js.map` should be added to the `.gitnore` and not committed

**Comment by EChesters** [comment]
Deleted the files and pushed a new commit to add them to the .gitignore 👍

**Comment by EChesters** [comment]
The bundle.js file appears to have been here before this commit. It is not going away and I'm not sure how to fix this 👎

**Comment by tanyapowell** [comment]
@EChesters drop me a message on slack when you're free and we'll go through it together 😄

**Review by tanyapowell — APPROVED** [review]

**Pull request merged**
